import os
from dotenv import load_dotenv 
from peewee import (
    PostgresqlDatabase, 
    Model, 
    CharField, 
    DecimalField, 
    Check, 
    UUIDField, 
    IntegerField, 
    SQL
)

# 1. Load the Environment Variables
load_dotenv()

# 2. Database Connection
db = PostgresqlDatabase(
    os.getenv('DB_NAME'),
    user=os.getenv('DB_USER'),
    password=os.getenv('DB_PASS'),
    host=os.getenv('DB_HOST', 'localhost'),
    port=int(os.getenv('DB_PORT', 5432))
)

class BaseModel(Model):
    class Meta:
        database = db

class Employee(BaseModel):
    # WHAT: Primary Key
    # WHY: You want the Keycloak UID to be the main unique identifier for GET/PUT/DELETE.
    uid = UUIDField(primary_key=True)

    # WHAT: Serial Number Column (Not a Primary Key)
    # WHY: This creates a column that Postgres automatically increments (1, 2, 3...).
    # 'constraints' tells Postgres to use its internal SERIAL logic.
    employee_id = IntegerField(constraints=[SQL('GENERATED BY DEFAULT AS IDENTITY')])

    name = CharField(max_length=100)
    email = CharField(unique=True, max_length=255)
    phone = CharField(max_length=20)
    designation = CharField(max_length=100)

    salary = DecimalField(
        max_digits=10, 
        decimal_places=2, 
        constraints=[Check('salary > 0')]
    )

    class Meta:
        table_name = 'employees'

def create_tables():
    """
    WHAT IT DOES:
    Creates the 'employees' table.
    """
    with db:
        db.create_tables([Employee])