from pydantic import BaseModel, Field, EmailStr
from uuid import UUID
from decimal import Decimal
from typing import Optional

class EmployeeBase(BaseModel):
    """
    WHAT: The base fields shared across all employee models.
    WHY: Keeps your code DRY (Don't Repeat Yourself).
    """
    email: EmailStr
    phone: str = Field(..., max_length=20)
    designation: str = Field(..., max_length=100)
    salary: Decimal = Field(..., gt=0, max_digits=12, decimal_places=2)

class EmployeeCreate(EmployeeBase):
    """
    WHAT: Schema for the POST /employees request.
    WHY: These are the only fields the user needs to fill in to register.
    """
    # We add these specifically for the creation form in Swagger
    first_name: str = Field(..., max_length=50)
    last_name: str = Field(..., max_length=50)

class EmployeeResponse(EmployeeBase):
    """
    WHAT: Schema for the API Response.
    WHY: Includes the fields generated by the system (UID and Serial Number).
    """
    uid: UUID
    name: str # The combined full name from the DB
    employee_id: int # The Serial number column

    class Config:
        from_attributes = True # Allows Pydantic to read Peewee/ORM objects